---
title: "Lecture 0: Lesson Plan Template"
subtitle: >
  {{< var course.code >}}, {{< var course.term >}}
number-sections: false
---

## Lecture overview
### Learning outcomes
- Learning outcome 1
- Learning outcome 2

### Pre-class work
::: {.content-hidden when-profile="student" when-profile="ta"}
#### Instructors
1. Do Thing 1.
2. Do Thing 2.

#### Coordinators
1. Do Thing 1.
2. Do Thing 2.
:::

::: {.content-hidden when-profile="student"}
#### TAs
1. Do Thing 1.
2. Do Thing 2.
:::

#### Learners
1. Do Thing 1.
2. Do Thing 2.

### Lecture timeline
::: {.list-table}
- - Topic
  - Time
  - Materials

- - [Topic 1](#sec-topic-1)
    - Key point 1
    - Key point 2
  - 20 min
  - Website 1

- - [Topic 2](#sec-topic-2)
    - Key point 1
    - Key point 2
  - 20 min

- - [Topic 3](#sec-topic-3)
    - Key point 1
    - Key point 2
  - 20 min
  - Website 2
:::

### Post-class work
::: {.content-hidden when-profile="student" when-profile="ta"}
#### Instructors
1. Do Thing 1.
2. Do Thing 2.

#### Coordinators
1. Do Thing 1.
2. Do Thing 2.
:::

::: {.content-hidden when-profile="student"}
#### TAs
1. Do Thing 1.
2. Do Thing 2.
:::

#### Learners
1. Do Thing 1.
2. Do Thing 2.

## Topic 1{#sec-topic-1}
- Text about topic 1.
- Further comments about topic 1.

### Subtopic 1.1
- Text about subtopic 1.1.
  - More details about subtopic 1.1.
  - Even more details about subtopic 1.1.

### Activity: Activity Name
- Instructions for activity.
- More instructions for activity.

## Topic 2{#sec-topic-2}
- Text about topic 2.
- Further comments about topic 2.

### Subtopic 2.1
- Text about subtopic 2.1.
  - More details about subtopic 2.1.

## Topic 3{#sec-topic-3}
- Text about topic 3.
- Further comments about topic 3.

### Activity: Activity Name
- Instructions for activity.
  - More instructions for activity.