import numpy as np
import plotly.graph_objects as go
import plotly.express as px


"""
Code generated by Claude Fable 5 and Opus 4.8, with some manual cleanup. Intended for use in lecture 4.

Interactive 3D teaching plots for class-separability demos.

Three public functions:

* boundary_plot_compare_2d -- points stay in 2D; a button toggles
  between two separators, each of which may be a line or a fitted
  decision tree.

* boundary_plot_2d_to_3d -- points toggle between a flat "2D view" and the
  full 3D view, with an optional 2D line (flat state) and 3D plane (risen
  state).

* boundary_plot_compare_3d -- points stay in 3D; a button toggles
  between two separators, each of which may be a plane or a fitted
  decision tree.
"""

# --------------------------------------------------------------------------
# Shared helpers
# --------------------------------------------------------------------------

def _class_traces(groups, feature_x, feature_y, feature_z, color_map, z_values):
    """Scatter3d trace per class. z_values(group) -> array of z coords."""
    return [
        go.Scatter3d(
            x=g[feature_x],
            y=g[feature_y],
            z=z_values(g),
            mode="markers",
            marker=dict(
                size=6,
                color=color_map[c],
                opacity=0.9,
                line=dict(color="black", width=1),
            ),
            name=str(c),
        )
        for c, g in groups.items()
    ]


def _default_color_map(categories):
    palette = px.colors.qualitative.Plotly
    return {c: palette[i % len(palette)] for i, c in enumerate(categories)}


def _single_color_surface(gx, gy, gz, color, opacity, visible, name, legend):
    return go.Surface(
        x=gx, y=gy, z=gz,
        colorscale=[[0, color], [1, color]],
        showscale=False,
        opacity=opacity,
        visible=visible,
        name=name,
        showlegend=legend,
        hoverinfo="skip",
    )


def _plane_grid(coef, intercept, bounds):
    """Grid for a*x + b*y + c*z + d = 0 clipped to the data box `bounds`.

    Solves over the dominant axes so near-vertical planes render too.
    """
    (x_min, x_max), (y_min, y_max), (z_min, z_max) = bounds
    a, b, c = coef
    d = intercept
    if abs(c) >= max(abs(a), abs(b)) * 1e-6 and abs(c) > 0:
        gx, gy = np.meshgrid(
            np.linspace(x_min, x_max, 30), np.linspace(y_min, y_max, 30)
        )
        gz = (-d - a * gx - b * gy) / c
        gz = np.where((gz >= z_min) & (gz <= z_max), gz, np.nan)
    elif abs(b) >= abs(a):
        gx, gz = np.meshgrid(
            np.linspace(x_min, x_max, 30), np.linspace(z_min, z_max, 30)
        )
        gy = (-d - a * gx - c * gz) / b
        gy = np.where((gy >= y_min) & (gy <= y_max), gy, np.nan)
    else:
        gy, gz = np.meshgrid(
            np.linspace(y_min, y_max, 30), np.linspace(z_min, z_max, 30)
        )
        gx = (-d - b * gy - c * gz) / a
        gx = np.where((gx >= x_min) & (gx <= x_max), gx, np.nan)
    return gx, gy, gz

def _padded_range(lo, hi, pad_frac=0.05):
    """Return a padded numeric axis range. Handles constant-valued columns."""
    lo = float(lo)
    hi = float(hi)
    span = hi - lo

    if span == 0:
        pad = abs(lo) * pad_frac if lo != 0 else 1.0
    else:
        pad = span * pad_frac

    return (lo - pad, hi + pad)

def _tree_rectangles(model, bounds):
    """All splitting rectangles of a fitted sklearn tree.

    Walks the tree tracking the bounding box each node governs. Each
    internal split (feature f at threshold thr) becomes an axis-aligned
    rectangle: f pinned at thr, the other two axes spanning that node's
    current box. Returns a list of (gx, gy, gz) grids.
    """
    t = model.tree_
    grids = []

    def recurse(node, box):
        f = t.feature[node]
        if f < 0:  # leaf
            return
        thr = float(t.threshold[node])
        u, v = (i for i in range(3) if i != f)
        gu, gv = np.meshgrid(
            np.linspace(box[u][0], box[u][1], 2),
            np.linspace(box[v][0], box[v][1], 2),
        )
        coords = [None, None, None]
        coords[f] = np.full_like(gu, thr)
        coords[u], coords[v] = gu, gv
        grids.append(tuple(coords))
        left = [b[:] for b in box]
        right = [b[:] for b in box]
        left[f][1] = thr
        right[f][0] = thr
        recurse(t.children_left[node], left)
        recurse(t.children_right[node], right)

    recurse(0, [list(b) for b in bounds])
    return grids


def _separator_surfaces(spec, bounds, default_name, visible):
    """Turn a separator spec into a list of Surface traces.

    Accepted specs:
      * plane coefficients (a, b, c, d)  for  a*x + b*y + c*z + d = 0
      * dict {"coef": (a, b, c), "intercept": d, ...style...}
      * a fitted sklearn decision tree (anything with `.tree_`)
      * dict {"model": fitted_tree, ...style...}
    Style keys: color, opacity, name.
    """
    style = spec if isinstance(spec, dict) else {}
    if isinstance(spec, dict) and "model" in spec:
        kind, payload = "tree", spec["model"]
    elif hasattr(spec, "tree_"):
        kind, payload = "tree", spec
    elif isinstance(spec, dict) and "coef" in spec:
        kind, payload = "plane", (spec["coef"], spec["intercept"])
    elif np.shape(spec) == (4,):
        kind, payload = "plane", (spec[:3], spec[3])
    else:
        raise ValueError(
            f"Can't interpret separator spec {spec!r}: expected plane "
            "coefficients (a, b, c, d), a dict with 'coef'/'intercept', a "
            "fitted decision tree, or a dict with 'model'."
        )

    name = style.get("name", default_name)
    if kind == "plane":
        coef, intercept = payload
        grids = [_plane_grid(coef, intercept, bounds)]
        color = style.get("color", "gray")
        opacity = style.get("opacity", 0.45)
    else:
        grids = _tree_rectangles(payload, bounds)
        color = style.get("color", "darkorange")
        opacity = style.get("opacity", 0.4)

    return [
        _single_color_surface(
            *g, color=color, opacity=opacity, visible=visible,
            name=name, legend=(k == 0),  # one legend entry per separator
        )
        for k, g in enumerate(grids)
    ]

def _scene_layout(fig, title, feature_x, feature_y, feature_z, x_range, y_range, z_range, buttons):
    fig.update_layout(
        title=title,
        scene=dict(
            xaxis_title=feature_x.replace("_", " "),
            yaxis_title=feature_y.replace("_", " "),
            zaxis_title=feature_z.replace("_", " "),
            xaxis=dict(range=list(x_range)),
            yaxis=dict(range=list(y_range)),
            zaxis=dict(range=list(z_range)),
            aspectmode="cube",
            camera=dict(eye=dict(x=1.5, y=1.5, z=1.3)),
        ),
        updatemenus=[
            dict(
                type="buttons",
                direction="left",
                buttons=buttons,
                pad=dict(r=10, t=10),
                x=0.1, xanchor="right",
                y=0, yanchor="bottom",
            )
        ],
        legend=dict(
            x=0.01, xanchor="left",
            y=0.99, yanchor="top",
            bgcolor="rgba(255, 255, 255, 0.5)",
        ),
        margin=dict(l=0, r=0, b=50, t=40),
    )


def _jump_args(frame_name):
    return [
        [frame_name],
        dict(
            frame=dict(duration=0, redraw=True),
            transition=dict(duration=0),
            mode="immediate",
        ),
    ]


def _bounds(df, feature_x, feature_y, feature_z):
    return [
        (df[feature_x].min(), df[feature_x].max()),
        (df[feature_y].min(), df[feature_y].max()),
        (df[feature_z].min(), df[feature_z].max()),
    ]


# --------------------------------------------------------------------------
# 2D helpers (analogues of the 3D ones above)
# --------------------------------------------------------------------------

def _class_traces_2d(groups, feature_x, feature_y, color_map):
    """One Scatter (2D) trace per class, at the points' true coordinates."""
    return [
        go.Scatter(
            x=g[feature_x],
            y=g[feature_y],
            mode="markers",
            marker=dict(
                size=8,
                color=color_map[c],
                opacity=0.9,
                line=dict(color="black", width=1),
            ),
            name=str(c),
        )
        for c, g in groups.items()
    ]


def _line_xy(coef, intercept, bounds):
    """Sampled points of a*x + b*y + c = 0 clipped to the data box.

    Solves over the dominant axis (NaN-masking the out-of-box part) so
    near-vertical lines render correctly.
    """
    (x_min, x_max), (y_min, y_max) = bounds
    a, b = coef
    c = intercept
    if abs(b) >= abs(a) and abs(b) > 0:
        xs = np.linspace(x_min, x_max, 60)
        ys = (-c - a * xs) / b
        ys = np.where((ys >= y_min) & (ys <= y_max), ys, np.nan)
    else:
        ys = np.linspace(y_min, y_max, 60)
        xs = (-c - b * ys) / a
        xs = np.where((xs >= x_min) & (xs <= x_max), xs, np.nan)
    return xs, ys


def _tree_segments_2d(model, bounds):
    """All splitting segments of a fitted 2-feature sklearn tree.

    Each internal split (feature f at threshold thr) becomes an
    axis-aligned segment: f pinned at thr, the other axis spanning that
    node's current box. Returns a list of (xs, ys) two-point segments.
    """
    t = model.tree_
    segs = []

    def recurse(node, box):
        f = t.feature[node]
        if f < 0:  # leaf
            return
        thr = float(t.threshold[node])
        if f == 0:  # vertical line x = thr, spanning the node's y-range
            xs, ys = [thr, thr], [box[1][0], box[1][1]]
        else:       # horizontal line y = thr, spanning the node's x-range
            xs, ys = [box[0][0], box[0][1]], [thr, thr]
        segs.append((xs, ys))
        left = [b[:] for b in box]
        right = [b[:] for b in box]
        left[f][1] = thr
        right[f][0] = thr
        recurse(t.children_left[node], left)
        recurse(t.children_right[node], right)

    recurse(0, [list(b) for b in bounds])
    return segs


def _separator_lines(spec, bounds, default_name, visible):
    """Turn a 2D separator spec into a list of Scatter line traces.

    Accepted specs:
      * line coefficients (a, b, c)  for  a*x + b*y + c = 0
        (sklearn: a, b = model.coef_[0], c = model.intercept_[0])
      * dict {"coef": (a, b), "intercept": c, ...style...}
      * a fitted sklearn decision tree (anything with `.tree_`) trained on
        exactly [feature_x, feature_y] IN THAT ORDER
      * dict {"model": fitted_tree, ...style...}
    Style keys: color, opacity, name, width, dash.
    """
    style = spec if isinstance(spec, dict) else {}
    if isinstance(spec, dict) and "model" in spec:
        kind, payload = "tree", spec["model"]
    elif hasattr(spec, "tree_"):
        kind, payload = "tree", spec
    elif isinstance(spec, dict) and "coef" in spec:
        kind, payload = "line", (spec["coef"], spec["intercept"])
    elif np.shape(spec) == (3,):
        kind, payload = "line", (spec[:2], spec[2])
    else:
        raise ValueError(
            f"Can't interpret separator spec {spec!r}: expected line "
            "coefficients (a, b, c), a dict with 'coef'/'intercept', a "
            "fitted decision tree, or a dict with 'model'."
        )

    name = style.get("name", default_name)
    if kind == "line":
        coef, intercept = payload
        segments = [_line_xy(coef, intercept, bounds)]
        color = style.get("color", "gray")
        width = style.get("width", 4)
    else:
        segments = _tree_segments_2d(payload, bounds)
        color = style.get("color", "darkorange")
        width = style.get("width", 3)

    return [
        go.Scatter(
            x=xs, y=ys, mode="lines",
            line=dict(color=color, width=width, dash=style.get("dash", "solid")),
            opacity=style.get("opacity", 1.0),
            visible=visible,
            name=name,
            showlegend=(k == 0),  # one legend entry per separator
            hoverinfo="skip",
        )
        for k, (xs, ys) in enumerate(segments)
    ]


def _scene_layout_2d(fig, title, feature_x, feature_y, x_range, y_range, buttons):
    fig.update_layout(
        title=dict(text=title, x=0, xanchor="left", y=0.97, yanchor="top"),
        xaxis=dict(title=feature_x.replace("_", " "), range=list(x_range)),
        yaxis=dict(title=feature_y.replace("_", " "), range=list(y_range)),
        updatemenus=[
            dict(
                type="buttons",
                direction="left",
                buttons=buttons,
                pad=dict(r=6, t=6),
                x=1, xanchor="right",   # top-right, away from the title
                y=1.12, yanchor="bottom",  # above the plot, not on the axis
                showactive=True,
            )
        ],
        legend=dict(
            x=0.01, xanchor="left",
            y=0.99, yanchor="top",
            bgcolor="rgba(255, 255, 255, 0.5)",
        ),
        margin=dict(l=60, r=20, b=60, t=90),  # t=90 makes room for title + buttons
    )

# --------------------------------------------------------------------------
# Function 1: fixed 2D view, toggle between two separators
# --------------------------------------------------------------------------

def boundary_plot_compare_2d(
    df,
    feature_x,
    feature_y,
    target,
    separator_a,
    separator_b,
    title=None,
    color_map=None,
):
    """Points stay in 2D; a button toggles between two separators.

    Each separator can independently be a line or a fitted decision tree:
      * line coefficients (a, b, c)  for  a*x + b*y + c = 0
        (sklearn: a, b = model.coef_[0], c = model.intercept_[0])
      * dict {"coef": (a, b), "intercept": c, "color": ..., "opacity": ...,
              "name": ..., "width": ..., "dash": ...}
      * a fitted sklearn DecisionTree(Classifier/Regressor) -- or anything
        with a compatible `.tree_` -- trained on exactly
        [feature_x, feature_y] IN THAT ORDER
      * dict {"model": fitted_tree, "color": ..., "opacity": ..., "name": ...}

    separator_a is shown first; the button swaps to separator_b and back.
    """
    categories = list(df[target].unique())
    color_map = color_map or _default_color_map(categories)
    groups = {c: df[df[target] == c] for c in categories}
    bounds = [
        (df[feature_x].min(), df[feature_x].max()),
        (df[feature_y].min(), df[feature_y].max()),
    ]

    # Points are static: drawn once at their true coordinates.
    fig = go.Figure(data=_class_traces_2d(groups, feature_x, feature_y, color_map))

    traces_a = _separator_lines(separator_a, bounds, "Separator A", visible=True)
    traces_b = _separator_lines(separator_b, bounds, "Separator B", visible=False)
    idx_a = list(range(len(fig.data), len(fig.data) + len(traces_a)))
    for tr in traces_a:
        fig.add_trace(tr)
    idx_b = list(range(len(fig.data), len(fig.data) + len(traces_b)))
    for tr in traces_b:
        fig.add_trace(tr)

    # Two frames flipping which separator's traces are visible. The class
    # scatter traces are not in `traces`, so the points never move.
    trace_ids = idx_a + idx_b

    def frame_data(show_a):
        return (
            [go.Scatter(visible=show_a) for _ in idx_a]
            + [go.Scatter(visible=not show_a) for _ in idx_b]
        )

    fig.frames = [
        go.Frame(name="a", traces=trace_ids, data=frame_data(show_a=True)),
        go.Frame(name="b", traces=trace_ids, data=frame_data(show_a=False)),
    ]

    name_a = traces_a[0].name
    name_b = traces_b[0].name

    x_range = _padded_range(*bounds[0])
    y_range = _padded_range(*bounds[1])

    _scene_layout_2d(
        fig,
        title or f"{name_a} vs {name_b}",
        feature_x,
        feature_y,
        x_range,
        y_range,
        buttons=[
            dict(label=f"Show {name_a}", method="animate", args=_jump_args("a")),
            dict(label=f"Show {name_b}", method="animate", args=_jump_args("b")),
        ],
    )

    fig.show()


# --------------------------------------------------------------------------
# Function 2: flat "2D" view  <->  3D view
# --------------------------------------------------------------------------

def boundary_plot_2d_to_3d(
    df,
    feature_x,
    feature_y,
    feature_z,
    target,
    title=None,
    color_map=None,
    line=None,
    plane=None
):
    categories = list(df[target].unique())
    color_map = color_map or _default_color_map(categories)
    groups = {c: df[df[target] == c] for c in categories}
    bounds = _bounds(df, feature_x, feature_y, feature_z)

    x_range = _padded_range(*bounds[0])
    y_range = _padded_range(*bounds[1])
    z_range = _padded_range(*bounds[2])

    z_min = bounds[2][0]

    flat_z = lambda g: np.full(len(g), z_min)

    fig = go.Figure(
        data=_class_traces(
            groups,
            feature_x,
            feature_y,
            feature_z,
            color_map,
            z_values=flat_z
        )
    )

    n_classes = len(categories)

    line_idx = None
    if line is not None:
        spec = line if isinstance(line, dict) else {"start": line[0], "end": line[1]}
        (lx0, ly0), (lx1, ly1) = spec["start"], spec["end"]

        line_idx = len(fig.data)
        fig.add_trace(
            go.Scatter3d(
                x=[lx0, lx1],
                y=[ly0, ly1],
                z=[z_min, z_min],
                mode="lines",
                line=dict(
                    color=spec.get("color", "black"),
                    width=spec.get("width", 6),
                    dash=spec.get("dash", "dash"),
                ),
                visible=True,
                name=spec.get("name", "2D boundary"),
                showlegend="name" in spec,
            )
        )

    plane_idx = None
    if plane is not None:
        plane_idx = len(fig.data)
        for tr in _separator_surfaces(plane, bounds, "3D boundary", visible=False):
            fig.add_trace(tr)

    trace_ids = list(range(n_classes))
    if line_idx is not None:
        trace_ids.append(line_idx)
    if plane_idx is not None:
        trace_ids.append(plane_idx)

    def frame_data(risen):
        z_values = (lambda g: g[feature_z]) if risen else flat_z

        data = _class_traces(
            groups,
            feature_x,
            feature_y,
            feature_z,
            color_map,
            z_values=z_values
        )

        if line_idx is not None:
            data.append(go.Scatter3d(visible=not risen))

        if plane_idx is not None:
            data.append(go.Surface(visible=risen))

        return data

    fig.frames = [
        go.Frame(name="flat", traces=trace_ids, data=frame_data(risen=False)),
        go.Frame(name="rise", traces=trace_ids, data=frame_data(risen=True)),
    ]

    _scene_layout(
        fig,
        title or f"{feature_x} & {feature_y}, then adding {feature_z}",
        feature_x,
        feature_y,
        feature_z,
        x_range,
        y_range,
        z_range,

        buttons=[
            dict(
                label="Show 3D",
                method="animate",
                args=_jump_args("rise"),
            ),
            dict(
                label="Show 2D",
                method="animate",
                args=_jump_args("flat"),
            ),
        ],
    )

    fig.show()


# --------------------------------------------------------------------------
# Function 3: fixed 3D view, toggle between two separators
# --------------------------------------------------------------------------

def boundary_plot_compare_3d(
    df,
    feature_x,
    feature_y,
    feature_z,
    target,
    separator_a,
    separator_b,
    title=None,
    color_map=None
):
    """Points stay in 3D; a button toggles between two separators.

    Each separator can independently be a plane or a fitted decision tree:
      * plane coefficients (a, b, c, d)  for  a*x + b*y + c*z + d = 0
        (sklearn: a, b, c = model.coef_[0], d = model.intercept_[0])
      * dict {"coef": (a, b, c), "intercept": d, "color": ..., "opacity": ...,
              "name": ...}
      * a fitted sklearn DecisionTree(Classifier/Regressor) -- or anything
        with a compatible `.tree_` -- trained on exactly
        [feature_x, feature_y, feature_z] IN THAT ORDER
      * dict {"model": fitted_tree, "color": ..., "opacity": ..., "name": ...}

    separator_a is shown first; the button swaps to separator_b and back.
    """
    categories = list(df[target].unique())
    color_map = color_map or _default_color_map(categories)
    groups = {c: df[df[target] == c] for c in categories}
    bounds = _bounds(df, feature_x, feature_y, feature_z)

    # Points are static: drawn once at their true coordinates.
    fig = go.Figure(
        data=_class_traces(groups, feature_x, feature_y, feature_z,
                           color_map, z_values=lambda g: g[feature_z])
    )

    traces_a = _separator_surfaces(separator_a, bounds, "Separator A", visible=True)
    traces_b = _separator_surfaces(separator_b, bounds, "Separator B", visible=False)
    idx_a = list(range(len(fig.data), len(fig.data) + len(traces_a)))
    for tr in traces_a:
        fig.add_trace(tr)
    idx_b = list(range(len(fig.data), len(fig.data) + len(traces_b)))
    for tr in traces_b:
        fig.add_trace(tr)

    # Two frames flipping which separator's traces are visible. The class
    # scatter traces are not in `traces`, so the points never move.
    trace_ids = idx_a + idx_b

    def frame_data(show_a):
        return (
            [go.Surface(visible=show_a) for _ in idx_a]
            + [go.Surface(visible=not show_a) for _ in idx_b]
        )

    fig.frames = [
        go.Frame(name="a", traces=trace_ids, data=frame_data(show_a=True)),
        go.Frame(name="b", traces=trace_ids, data=frame_data(show_a=False)),
    ]

    name_a = traces_a[0].name
    name_b = traces_b[0].name

    x_range = _padded_range(*bounds[0])
    y_range = _padded_range(*bounds[1])
    z_range = _padded_range(*bounds[2])

    _scene_layout(
        fig,
        title or f"{name_a} vs {name_b}",
        feature_x,
        feature_y,
        feature_z,
        x_range,
        y_range,
        z_range,
        buttons=[
            dict(
                label=f"Show {name_a}",
                method="animate",
                args=_jump_args("a"),
            ),
            dict(
                label=f"Show {name_b}",
                method="animate",
                args=_jump_args("b"),
            ),
        ],
    )

    fig.show()